package uz.softex.securitystore.position.entity;

public enum PositionTypes {
    ADD_ADDRESS,
    EDIT_ADDRESS,
    DELETE_ADDRESS,
    VIEW_ADDRESS,


    ADD_STORE,
    DELETE_STORE,
    EDIT_STORE,
    VIEW_STORE,
    VIEW_MY_STORE,


    ADD_DIRECTOR,
    DELETE_DIRECTOR,
    EDIT_DIRECTOR,
    VIEW_DIRECTOR,


    ADD_POSITION,
    DELETE_POSITION,
    EDIT_POSITION,
    VIEW_POSITION,


    ADD_INPUTS,
    DELETE_INPUTS,
    EDIT_INPUTS,
    VIEW_INPUTS,


    ADD_OUTPUTS,
    DELETE_OUTPUTS,
    EDIT_OUTPUTS,
    VIEW_OUTPUTS,


    ADD_WORKER,
    DELETE_WORKER,
    EDIT_WORKER,
    VIEW_MY_WORKERS,
    BLOCK_OR_UNBLOCK,
    CHANGE_MY_PASSWORD,

    ADD_PRODUCT,
    DELETE_PRODUCT,
    EDIT_PRODUCT,
    VIEW_MY_PRODUCTS,
    FILTER_PRODUCTS
}
